Lesson 1 Problem 1

In [13]:
import numpy as np

In [14]:
a = np.array([[1,6],
            [2,8],
            [3,11],
            [3,10],
            [1,7]])
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [15]:
mean_a = a.mean(axis=0)
print("Average value of a feauture:{}".format(mean_a))

Average value of a feauture:[2.  8.4]


In [16]:
a_centered = a - a.mean(axis=0)
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


Problem 3

In [17]:
a_centered_sp1 = a_centered[:,0]
print(a_centered_sp1)

[-1.  0.  1.  1. -1.]


In [18]:
a_centered_sp2 = a_centered[:,1]
print(a_centered_sp2)

[-2.4 -0.4  2.6  1.6 -1.4]


In [19]:
a_centered_sp = a_centered_sp1.dot(a_centered_sp2)
print(a_centered_sp)

8.0


In [20]:
N = a_centered_sp1.size
print(N)

5


In [21]:
final = a_centered_sp/(N-1)
final

2.0

Problem 4

In [22]:
a = np.array([[1,6],
            [2,8],
            [3,11],
            [3,10],
            [1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [23]:
m = np.cov(a.transpose())
m

array([[1. , 2. ],
       [2. , 4.3]])

In [24]:
cov=m[0,1]
cov

2.0

Pandas

Problem 1

In [25]:
import pandas as pd

In [26]:
authors = pd.DataFrame({'author_id': [1, 2, 3], 'author_name': ["Turgenev", "Chekhov", "Ostrovsky"]})
print(authors)

   author_id author_name
0          1    Turgenev
1          2     Chekhov
2          3   Ostrovsky


In [27]:
books = pd.DataFrame({'author_id': [1, 1, 1, 2, 2, 3, 3], 
                     'book_title':['Fathers and Sons','Rudin', 'Noble Nest', 'Fat and Thin', 
                                   'Lady with The Dog', 'The Storm', 'Talents and Admirers'],
                     'price':[450, 300, 350, 500, 450, 370, 290]})
print(books)


   author_id            book_title  price
0          1      Fathers and Sons    450
1          1                 Rudin    300
2          1            Noble Nest    350
3          2          Fat and Thin    500
4          2     Lady with The Dog    450
5          3             The Storm    370
6          3  Talents and Admirers    290


Problem 2

In [28]:
authors_price = pd.merge(authors, books, on='author_id', how='inner')
authors_price

author_id author_name            book_title  price
0          1    Turgenev      Fathers and Sons    450
1          1    Turgenev                 Rudin    300
2          1    Turgenev            Noble Nest    350
3          2     Chekhov          Fat and Thin    500
4          2     Chekhov     Lady with The Dog    450
5          3   Ostrovsky             The Storm    370
6          3   Ostrovsky  Talents and Admirers    290

Problem 3

In [29]:
top5 = pd.DataFrame(authors_price.nlargest(5, 'price'))
top5

author_id author_name         book_title  price
3          2     Chekhov       Fat and Thin    500
0          1    Turgenev   Fathers and Sons    450
4          2     Chekhov  Lady with The Dog    450
5          3   Ostrovsky          The Storm    370
2          1    Turgenev         Noble Nest    350

Problem 4

In [30]:
as1 = authors_price.groupby('author_name').agg({'price': 'mean'}).rename(columns={'price':'mean_price'})

In [31]:
as2 = authors_price.groupby('author_name').agg({'price': 'min'}).rename(columns={'price':'min_price'})

In [32]:
as3 = authors_price.groupby('author_name').agg({'price': 'max'}).rename(columns={'price':'max_price'})

In [33]:
authors_stat = pd.concat([as1,as2,as3], axis = 1)
authors_stat

mean_price  min_price  max_price
author_name                                  
Chekhov      475.000000        450        500
Ostrovsky    330.000000        290        370
Turgenev     366.666667        300        450

Problem 5


Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.


In [34]:
authors_price['cover'] = ['hardcover', 'paperback', 'paperback', 'hardcover', 'hardcover', 'paperback', 'paperback']
authors_price

author_id author_name            book_title  price      cover
0          1    Turgenev      Fathers and Sons    450  hardcover
1          1    Turgenev                 Rudin    300  paperback
2          1    Turgenev            Noble Nest    350  paperback
3          2     Chekhov          Fat and Thin    500  hardcover
4          2     Chekhov     Lady with The Dog    450  hardcover
5          3   Ostrovsky             The Storm    370  paperback
6          3   Ostrovsky  Talents and Admirers    290  paperback

In [46]:
book_info = pd.pivot_table(authors_price , values='price', index= ['author_name'],
...                     columns=['cover'], aggfunc=np.sum)
book_info

cover        hardcover  paperback
author_name                      
Chekhov          950.0        NaN
Ostrovsky          NaN      660.0
Turgenev         450.0      650.0

In [57]:
book_info["hardcover"].fillna(0, inplace=True)
book_info["paperback"].fillna(0, inplace=True)
book_info

cover        hardcover  paperback
author_name                      
Chekhov          950.0        0.0
Ostrovsky          0.0      660.0
Turgenev         450.0      650.0

In [74]:
book_info.to_pickle("book_info.pkl", compression='infer', protocol=5, storage_options=None)

In [75]:
book_info2 = pd.read_pickle("book_info.pkl",compression='infer', storage_options=None)
book_info2

cover        hardcover  paperback
author_name                      
Chekhov          950.0        0.0
Ostrovsky          0.0      660.0
Turgenev         450.0      650.0